id: P010706
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG13017
  title: གཉུག་སེམས་སྐོར་གསུམ་དང་གཞུང་སྤྱིའི་དཀའ་གནད།
  author: ''
  volumes:
    621e8b98076f42a2b2cb35677f779932:
      image_group_id: I1KG13095
      title: ''
      volume_number: 1
      total_pages: 468
      base_file: v001.txt
