id: I24D8D2C9
legacy_id: P010706
ocr_import_info:
  bdrc_scan_id: W1KG13017
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T13:40:50'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T04:35:21.389978+00:00'
last_modified: 2022-08-27 12:36:06.426277
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG13017
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG13017
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཉུག་སེམས་སྐོར་གསུམ་དང་གཞུང་སྤྱིའི་དཀའ་གནད།
  author: འཇུ་མི་ཕམ་འཇམ་དབྱངས་རྣམ་རྒྱལ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.938321541423412
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG13095:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG13095
      total_pages: 468
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG13095.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.938321541423412
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
